---
title: "ex33_code"
author: "ian jonsen"
date: "26/05/2021"
output: html_document
---

```{r knitr_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, message=FALSE, warning=FALSE}
require(tidyverse, quietly = TRUE)
require(foieGras, quietly = TRUE)
```

### Infer movement persistence along southern elephant seal tracks
```{r fit SSM, eval=FALSE, message=FALSE, warning=FALSE}
load("../data/ex32_sese.RData")

fit <- fit_ssm(sese, vmax=3, model="mp", time.step=12, control=ssm_control(verbose=0))

save(fit, file = "../data/ex32_fit.RData", compress="xz")
```

### Use alternate prediction intervals to assess influence on movement persistence estimation
```{r use diff pred ints, eval=TRUE, message=FALSE, warning=FALSE}
ts <- c(6,12,18,36,48)
fmp.pi <- lapply(1:5, function(i) {
  f <- fit_ssm(sese, vmax=4, model="crw", time.step=ts[i], control=ssm_control(verbose=0, se=FALSE))
  fit_mpm(f, what = "predicted", model = "jmpm", control = mpm_control(verbose = 0))
})
saveRDS(fmp.pi, file = "../data/ex33_fmp.pi.RDS", compress="xz")
```


### visualise movement persistence in 1-D time-series plots
```{r mp time-series plots}
load("../data/ex33_fmp.RData")
plot(fmp, pages = 1, ncol=2, ask=0, pal = "Cividis")

```

### map movement persistence along animal tracks
```{r map mp}
fmap(fit, fmp, what = "p", crs = "+proj=stere +lon_0=70 +units=km +datum=WGS84 +no_defs", pal="Cividis")
```

