---
title: "ex32_code"
author: "ian jonsen"
date: "10/11/2021"
output: html_document
---

```{r knitr_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, message=FALSE, warning=FALSE}
require(tidyverse, quietly = TRUE)
require(foieGras, quietly = TRUE)
require(patchwork, quietly = TRUE)
require(ggspatial, quietly = TRUE)
require(sf, quietly = TRUE)
```

#### Read little penguin GPS data and fit SSM to 5 penguin tracks with a regular 5-min prediction interval. 
```{r GPS data & fit SSM, message=FALSE, warning=FALSE, eval=TRUE}
peng <- readRDS("../data/ex32_lipe_gps_tracks.RDS")

fit <- fit_ssm(peng, 
               min.dt = 5,
               model = "crw",
               time.step = 5/60,
               control = ssm_control(verbose = 0)
               )
```

#### Now fit the mpm to the SSM-predicted locations
```{r fit mpm, message=FALSE, warning=FALSE, eval=TRUE}
fmp <- fit_mpm(fit, what="p", model = "jmpm", control = mpm_control(verbose = 0))
```

```{r save outputs, echo=FALSE, eval=TRUE}
svm.pc <- readRDS("../data/SVM-preycapture.RDS")
names(svm.pc)[3] <- "date"
save(peng, fit, fmp, svm.pc, file = "../data/ex32_lipe.RData", compress="xz")
```

```{r read data & fits, echo=TRUE}
load("../data/ex32_lipe.RData")
```


#### Plot move persistence time-series for 5-min prediction interval & map move persistence estimates along SSM-predicted tracks
```{r mp estimates, fig.width=10, fig.height=10, message=FALSE, warning=FALSE}

p <- plot(fmp, pages = 1, ncol = 3, ask = FALSE, pal = "Cividis") &
  theme(legend.position = "none")

peng.ssm_sf <- grab(fit, "p") %>%
  mutate(g = foieGras::grab(fmp, "f")$g) %>%
  sf::st_as_sf(., coords = c("lon","lat"), crs = 4326)
bb <- sf::st_bbox(peng.ssm_sf)

m <- ggplot() + 
  ggspatial::annotation_map_tile("cartolight", zoomin=0) +
  geom_sf(data = subset(peng.ssm_sf, g >= 0.5), aes(colour = g)) +
  geom_sf(data = subset(peng.ssm_sf, g < 0.5), aes(colour = g)) +
  scale_colour_viridis_c(option = "E", limits = c(0,1)) +
  theme_minimal() +
  guides(colour = guide_colourbar(title = expression(gamma[t]))) +
  coord_sf(xlim = extendrange(r=c(bb["xmin"]-0.05, bb["xmax"]), f= 0.1), 
           ylim = extendrange(r=c(bb["ymin"], bb["ymax"]), f= 0.1),
           crs = 4326) +
  ggspatial::annotation_scale(height = unit(0.15, "cm"), aes(location = "br")) +
  theme(legend.position = "none") +
  facet_wrap(~ id, ncol = 3)

p / m +
  plot_layout(heights = c(4,8)) +
  plot_annotation(tag_levels = "a") &
  theme(plot.title = element_blank())
```



