### simulate tracks, randomly subsample & estimate move persistence
```{r simulate 2-state crw, fig.width=10, echo=FALSE, eval=FALSE}

psim1 <- sim(N=1200, 
            start = list(c(150.21, -35.26),  
                         as.POSIXct(format(Sys.time(), tz = "UTC", usetz = TRUE))
                         ), 
            model = "crw", 
            D=c(40,20), 
            tdist="reg", 
            ts=0.5/60, 
            error="ls", 
            tau = c(0.00001, 0.00001), 
            alpha = c(0.8, 0.9))

foo <- psim1[sort(sample(1:1200, size=600, replace = FALSE)), ] %>% 
  mutate(id=1) %>% 
  select(id,date,lon,lat) %>% 
  fit_mpm(., model = "mpm", control = mpm_control(verbose=0))

ggplot() + 
  geom_point(data=psim1, aes(date, b, col=b), size=0.5) + 
  scale_colour_viridis_b(option="E") + 
  ylim(0,3) + 
  geom_line(data = grab(foo, "fitted"), aes(date, 1-g+1))

```

```{r simulate mpm, fig.width=10}
psim2 <- lapply(1:5,
                function(i) {
                  x <- sim(
                    N = 500,
                    model = "mpm",
                    sigma = c(0.001, 0.001),
                    sigma_g = 0.29,
                    tdist = "reg",
                    ts = 2,
                    error = "ls",
                    tau = c(0.0001, 0.0001),
                    rho_o = 0
                  ) %>%
                    mutate(dt = lubridate::as_date(date))
                  udt <- unique(x$dt)
                  drop_dts <-
                    sample(udt, size = round(length(udt) * 0.25), replace = FALSE) %>%
                    sort()
                  x %>% 
                    mutate(keep = !dt %in% drop_dts) %>%
                    mutate(id = i) %>%
                    select(id, everything())
                }) %>%
  do.call(rbind, .)

# udt <- unique(psim2$dt)
# drop_dates <- sample(udt, size = round(length(udt) * 0.25), replace = FALSE) %>%
#   sort()
# idx <- which(!psim2$dt %in% drop_dates)

fit <- psim2 %>%
  mutate(lc="G") %>% 
  filter(keep) %>%
  select(id,date,lc,lon,lat) %>% 
  fit_ssm(., 
          model="crw", 
          time.step=2, 
          map = list(rho_o = factor(NA)))
fmp <- fit_mpm(fit, what="p", model="mpm", control = mpm_control(verbose = 0))
fmf <- fit_mpm(fit, what="f", model="mpm", control = mpm_control(verbose = 0))


ggplot() + 
  geom_ribbon(data = grab(fmp, "fitted"),
              aes(date, 
                  ymin = plogis(qlogis(g) - 1.96 * g.se),
                  ymax = plogis(qlogis(g) + 1.96 * g.se)
                  ),
              fill = grey(0.5),
              alpha = 0.25) +
  geom_point(data = psim2, aes(date, g, colour = g), size = 0.9) +
  geom_line(data = grab(fmp, "fitted"), aes(date, g), colour = "firebrick") +
  geom_line(data = grab(fmf, "fitted"), aes(date, g), colour = "dodgerblue") +
  scale_colour_viridis_c(option="E") + 
  ylim(0,1) + 
  theme_minimal() + facet_wrap(~id, ncol = 3)

rmse.p <- sqrt(mean((qlogis(grab(fmp, "fitted")$g) - qlogis(psim2[-nrow(psim2),]$g))^2))
rmse.f <- sqrt(mean((qlogis(grab(fmf, "fitted")$g) - qlogis(psim2[idx,]$g))^2))



```
