---
title: "ex32_code"
author: "ian jonsen"
date: "26/05/2021"
output: html_document
---

```{r knitr_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, message=FALSE, warning=FALSE}
require(tidyverse, quietly = TRUE)
require(foieGras, quietly = TRUE)
```

### simulate `mpm` and `2-state crw` tracks & fit `rw` and `crw` SSM's
```{r simulate data, eval=FALSE}
set.seed(pi)
## mpm tracks
smpm <- lapply(1:50,
               function(i) {
                 sim(
                   N = 300,
                   ts = 6,
                   model = "mpm",
                   sigma_g = 0.25,
                   sigma = c(10, 6),
                   rho_p = 0.67,
                   error = "kf",
                   tdist = "reg"
                 ) %>% mutate(id = i) %>%
                   select(id, everything()) %>%
                   mutate(d = c(NA, sqrt(diff(x)^2 + diff(y)^2)))
               }) %>%
  do.call(rbind, .)

## 2-state crw tracks
s2crw <- lapply(1:50,
               function(i) {
                 sim(
                   N = 300,
                   ts = 6,
                   model = "crw",
                   D = c(0.05, 0.005),
                   alpha = c(0.95, 0.9),
                   error = "kf",
                   tdist = "reg"
                 ) %>% mutate(id = i) %>%
                   select(id, everything()) %>%
                   mutate(d = c(NA, sqrt(diff(x)^2 + diff(y)^2)))
               }) %>%
  do.call(rbind, .)

## crw tracks
scrw <- lapply(1:50,
               function(i) {
                 sim(
                   N = 300,
                   ts = 6,
                   model = "crw",
                   D = 0.02,
                   error = "kf",
                   tdist = "reg"
                 ) %>% mutate(id = i) %>%
                   select(id, everything()) %>%
                   mutate(d = c(NA, sqrt(diff(x)^2 + diff(y)^2)))
               }) %>%
  do.call(rbind, .)


## rw ssm fits
fmpm.rw <- fit_ssm(smpm %>% select(id,date,lc,lon,lat,smaj,smin,eor), 
                   model="rw", 
                   time.step=12,
                   control = ssm_control(verbose = 0))
f2crw.rw <- fit_ssm(s2crw %>% select(id,date,lc,lon,lat,smaj,smin,eor), 
                   model="rw", 
                   time.step=12,
                   control = ssm_control(verbose = 0))
fcrw.rw <- fit_ssm(scrw %>% select(id,date,lc,lon,lat,smaj,smin,eor), 
                   model="rw", 
                   time.step=12,
                   control = ssm_control(verbose = 0))

## crw ssm fits
fmpm.crw <- fit_ssm(smpm %>% select(id,date,lc,lon,lat,smaj,smin,eor), 
                   model="crw", 
                   time.step=12,
                   control = ssm_control(verbose = 0))
f2crw.crw <- fit_ssm(s2crw %>% select(id,date,lc,lon,lat,smaj,smin,eor), 
                   model="crw", 
                   time.step=12,
                   control = ssm_control(verbose = 0))
fcrw.crw <- fit_ssm(scrw %>% select(id,date,lc,lon,lat,smaj,smin,eor), 
                   model="crw", 
                   time.step=12,
                   control = ssm_control(verbose = 0))

save(smpm, s2crw, scrw, file = "../data/ex32_simdat.RData", compress = "xz")
save(fmpm.rw, f2crw.rw, fcrw.rw, fmpm.crw, f2crw.crw, fcrw.crw, file = "../data/ex32_ssmfit.RData", compress = "xz")
```

```{r calculate fit metrics, eval=FALSE}
load("../data/ex32_simdat.RData")
load("../data/ex32_ssmfit.RData")

## calculate distance b/w estimated and simulated locations

## merge relevant parts of sim data
simdat <- bind_rows(smpm %>% select(id, date, x, y, s=g),
                    s2crw %>% select(id, date, x, y, s=b),
                    scrw %>% select(id, date, x, y) %>% mutate(s=NA)) %>%
  mutate(model = factor(rep(c("mpm","2crw","crw"), each = 50*300))) %>%
  mutate(id = as.character(id))

rw.fits <- bind_rows(grab(fmpm.rw, "fitted") %>% select(id, date, x.hat=x, y.hat=y),
                     grab(f2crw.rw, "fitted") %>% select(id, date, x.hat=x, y.hat=y),
                     grab(fcrw.rw, "fitted") %>% select(id, date, x.hat=x, y.hat=y)) %>%
  mutate(smodel = factor(rep(c("mpm","2crw","crw"), c(nrow(grab(fmpm.rw, "f")),
                                                           nrow(grab(f2crw.rw, "f")),
                                                           nrow(grab(fcrw.rw, "f")))
                             )))

crw.fits <- bind_rows(grab(fmpm.crw, "fitted") %>% select(id, date, x.hat=x, y.hat=y),
                     grab(f2crw.crw, "fitted") %>% select(id, date, x.hat=x, y.hat=y),
                     grab(fcrw.crw, "fitted") %>% select(id, date, x.hat=x, y.hat=y)) %>%
  mutate(smodel = factor(rep(c("mpm","2crw","crw"), c(nrow(grab(fmpm.crw, "f")),
                                                           nrow(grab(f2crw.crw, "f")),
                                                           nrow(grab(fcrw.crw, "f")))
                             )))

## merge sim, fitted data & calculate RMSE
d.rw <- left_join(simdat, rw.fits, by = c("id","date", "model" = "smodel")) 
d.crw <- left_join(simdat, crw.fits, by = c("id","date", "model" = "smodel"))
rmse <- bind_rows(d.rw, d.crw) %>%
  mutate(SSM = factor(rep(c("rw","crw"), c(nrow(d.rw), nrow(d.crw))))) %>%
  select(id, sim=model, SSM, x, y, x.hat, y.hat) %>%
  filter(!is.na(x.hat) & !is.na(y.hat)) %>%
  mutate(dist = sqrt((x - x.hat)^2 + (y - y.hat)^2)) %>%
  group_by(sim, SSM, id) %>%
  mutate(d = c(NA,sqrt(diff(x)^2 + diff(y)^2))) %>%
  summarise(md = median(d, na.rm = TRUE),
            mae = mean(dist),
            rmse = sqrt(mean(dist^2)), 
            nrmse = sqrt(mean(dist^2)) / mean(d, na.rm = TRUE), 
            .groups = "drop") %>%
  mutate(sim = factor(as.character(sim), levels=c("crw", "2crw", "mpm"), labels=c("CRW", "2-CRW", "MPM"), ordered=TRUE))

save(rmse, file = "../data/ex32_rmse.RData", compress = "xz")
```


```{r plot RMSEs, echo=FALSE, fig.width=5, fig.height=6}
load("../data/ex32_rmse.RData")

## plot overall rmse's
ggplot(rmse, aes(SSM, rmse, fill = SSM)) +
    geom_boxplot() + facet_wrap(~sim, ncol=3)

## plot overall normalised rmse's
ggplot(rmse, aes(SSM, nrmse, fill = SSM)) +
  geom_boxplot() + 
  facet_wrap(~sim, ncol=3) +
  xlab("SSM process model") +
  ylab("Normalised RMSE") +
  theme(legend.position = "none") +
  ylim(0, 1.25)

ggplot(rmse, aes(SSM, mae, fill = SSM)) +
geom_boxplot() + 
  facet_wrap(~sim, ncol=3) +
  xlab("SSM process model") +
  ylab("Mean absolute error") +
  theme(legend.position = "none")

## select example simulated tracks & fits to plot

```





```

