---
title: "Appendix S2: Code for Application 3.2 seals"
author: "Jonsen et al"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load required R packages
```{r load pkgs, eval=FALSE, message=FALSE}
require(tidyverse)
require(ggspatial)
require(ggforce)
require(patchwork)
require(sf)
require(foieGras)
```

### Fit `mp` SSM with 12-h `time.step` to infer movement persistence along 4 southern elephant seal tracks
```{r fit SSM, eval=FALSE, message=FALSE}

## Load data from .csv file
sese <- read.csv("../data/sese_ex32.csv")

## fit `mp` SSM, using speed filter of 4 m/s to exclude extreme observations
fit <- fit_ssm(sese, vmax=4, model="mp", time.step=12)
```

### Plot move persistence estimates as time-series, 1 panel per seal
```{r mp time-series, eval=FALSE, message=FALSE}

## Normalise the gamma_t estimates so they span the interval 0, 1, grouping all
##  seals together so estimates are comparable among seals. 
p1 <- plot(fit, 
           type = 3, 
           pages = 1, 
           ncol = 2, 
           normalise = TRUE,
           group = TRUE,
           pal = "Plasma") & 
  ylim(0, 1) &
  theme(legend.position = "none",
        axis.text = element_text(size = 7))
```

### Map move persistence estimates along the SSM-estimated seal tracks
```{r map, eval=FALSE, message=FALSE, fig.width=6, fig.height=7}

## customise mapping aesthetics
my.aes <- aes_lst(conf = FALSE, 
                  line = TRUE)
my.aes$df$size[1] <- 1.5
my.aes$df$size[3] <- 0.1
my.aes$df$col[3] <- grey(0.3)
my.aes$df$fill[5] <- grey(0.4)
my.aes$df$fill[6] <- grey(0.6)

## project map, add scale bar using ggspatial::annotation_scale
m1 <- map(fit, 
          what = "p", 
          aes = my.aes,
          crs = "+proj=stere +lon_0=95 +units=km +datum=WGS84 +no_defs",
          normalise = TRUE, 
          group = TRUE,
          silent = TRUE) +
  xlab(element_blank()) +
  ylab(element_blank()) +
  ggspatial::annotation_scale(height = unit(1.25, "mm"), 
                              aes(width_hint = 0.2,
                                  location = "br",
                                  text_col = "white")) + 
  theme(legend.position = c(0.95,0.5), 
        legend.direction = "vertical",
        legend.key.width = unit(4, "mm"),
        legend.key.height = unit(7, "mm"),
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 7),
        axis.text = element_text(size = 7),
        panel.grid = element_line(colour = "white"))

## define bounding box based on SSM-predicted locations - for map annotations
bb <- grab(fit, what = "p", as_sf = TRUE) %>%
  sf::st_transform(., crs = m1$coordinates$crs) %>%
  sf::st_bbox()

## create track labels & highlight circles for map annotations
label.df <- data.frame(tag = c("a","b","c","d"), 
                        x = c(0.75, 0.9, 0.19, 0.53) * 
                         (bb["xmax"] - bb["xmin"]) + bb["xmin"],
                        y = c(0.32, 0.75, 0.2, 0.25) * 
                         (bb["ymax"] - bb["ymin"]) + bb["ymin"])
circle.df <- data.frame(x = c(0.25, 0.365, 0.485, 0.71) *
                          (bb["xmax"] - bb["xmin"]) + bb["xmin"],
                        y = c(0.11, 0.19, 0.24, 0.26) * 
                         (bb["ymax"] - bb["ymin"]) + bb["ymin"],
                        r = c(125,125,125,145)
                       )

## add track labels & highlight circles to map
m1 <- m1 + 
  geom_text(data = label.df, 
            aes(x, y, label=tag),
            size = 3) +
  ggforce::geom_circle(aes(x0 = circle.df$x, y0 = circle.df$y, r = circle.df$r),
             fill = NA,
             size = 0.8,
             colour = "dodgerblue")

## arrange panels & render Figure 2 using the `patchwork` package
(p1 | m1) +
  patchwork::plot_layout(nrow = 2, 
              heights = c(2, 5), 
              guides = "keep") +
  patchwork::plot_annotation(tag_levels = "a") &
  theme(plot.title = element_blank(),
        plot.tag = element_text(size = 9, colour = "black"))

```
