---
output:
  word_document: default
  html_document: default
---
# 1 | Introduction

```{r part_1_premble, include=FALSE}
#### Code for part 1: Introduction ####
```
The use of animal-borne electronic sensors has matured, with tracking data now virtually essential for understanding behaviour and social interactions, foraging ecology, physiology, habitat use and population dynamics of mobile and/or cryptic species. The sophistication of current technology also enables the use of animal-borne sensors as a cost-effective approach for observing our planet that compliments more traditional observing platforms [@Kays:2015;@Harcourt:2019;@McMahon:2021]. In all these applications, data from electronic tracking devices require rigourous quality control procedures to account for common, though not universally present, issues such as irregularly timed measurements, sensor biases and location measurement error. Some of these issues may be handled by a manufacturer's on-board or post-processing algorithms and some must be addressed by researchers using the data.

State-space models (SSMs) and hidden Markov models (HMMs) are powerful tools for conducting quality control of and making behavioural inference from animal tracking data [@Patterson:2008;@Jonsen:2013]. These are time-series models used across a wide range of research disciplines that estimate the state of an unobserved process from an observed data set. Here, we view an animal's true location and/or behaviour as the unobserved state(s), though many other types of states are possible [e.g., @Schick:2013;@Hooten:2019], and measurements recorded by electronic devices provide the observations. In practical yet simplistic terms, SSMs are usually preferred when the goal is to quality control error-prone location data and/or make inference directly from the parameters of their underlying movement models. HMMs are usually preferred when measurements have negligible error and occur at regular time intervals [but see @McClintock:2018], and when the goal is to infer behavioural states hidden within the data along with their potential external or internal drivers. Other more technical distinctions and reasons for preferring one of these methods exist [@Jonsen:2013;@Patterson:2017]. Our primary focus here is on SSMs as tools for quality control of error-prone location data and for making fast inference of behavioural changes along animal tracks. 

A number of R packages such as `moveHMM` [@Michelot:2016], `momentuHMM` [@McClintock:2018], and `swim` [@Whoriskey:2017] provide highly accessible and flexible tools for fitting HMMs to animal tracking data, and facilitating general inference of animal movement behaviour and its drivers. Similarly, R packages such as `bsam` [@Jonsen:2005], `crawl` [@Johnson:2008], `argosTrack` [@Albertsen:2015], `ctmm` [@Calabrese:2016], and `yaps` [@Baktoft:2017] all provide tools for fitting movement process models in either discrete- or continuous-time, ranging from simple random walks to Ornstein-Uhlenbeck processes, in state-space form to various types of tracking data. 

Here, we introduce the package `foieGras`, pronounced "*fwah grah*", developed for R [@RCore:2021]. This package was developed with two aims: (1) to be a simple and fast implementation of SSMs for quality control of error-prone animal (re)location data (including via Argos satellite, @Argos:2016;Jonsen:2020); and (2) for inference of changes in behaviour along animal movement tracks [@Jonsen:2019]. The simplicity of use sets `foieGras` apart from many of the related SSM R packages listed above, yet users can exert control over many aspects of the package functions via optional arguments. This design accommodates both novice and experienced users.

Here, we describe the main features of `foieGras` and illustrate its use through a set of applications drawing on Argos and GPS tracking data. Full R code and data for each of the applications is provided in the Supporting Information. Additional details on package functions and their use can be found in their help files and in the package vignettes. 

  

