# 4 | Conclusions

```{r part_4_preamble, include=FALSE}
#### Code for part 4: Conclusions ####
```
The `foieGras` package was developed to ease fitting state-space models for quality control of animal location data and for inference of behavioural change along animal tracks. We achieve these primarily through a simple yet extensible workflow, simple movement models, and computational speed. Combined, these traits accommodate both novice or occasional and advanced users, and facilitate use in automated, operational quality-assurance/quality-control processes for animal-borne sensor data \citep[e.g., the AniBOS network][]{McMahon:2021}. 

The `foieGras` package is an intermediate analysis toolbox where location quality control typically occurs after some initial data processing but prior to any comprehensive, final analysis. Similarly, the move persistence models rapidly identify changes in movement behaviour along animal tracks without any required *a priori* knowledge about the kind or number of behavioural states potentially hidden within the data. Subsequent, detailed behavioural analysis could entail use of a hidden Markov model to infer potential drivers of observed movements \citep[e.g., using the `moveHMM` or `momentuHMM` R packages][]{Michelot:2016,McClintock:2018}. Alternatively, move persistence - covariate relationships among multiple individuals can be inferred rapidly in a mixed-effects model framework using the `mpmm` R package \citep[][https://github.com/ianjonsen/mpmm]{Jonsen:2019}. 

The `foieGras` track simulation tools support habitat usage analyses, allowing habitat availability \citep{Aarts:2012} to be estimated by generating 'background' points representing a null model of the distribution of foraging animals in the absence of external drivers \citep{Raymond:2015}. As the generation of such null locations can impact the performance of habitat usage models \citep{Phillips:2009}, `foieGras` allows simulated tracks to be filtered based on their similarity to the SSM-predicted tracks. Eventually, `foieGras` will also allow simulation from the `posterior` of SSM-predicted tracks, whereby the simulated tracks are constrained by the estimated locations and their uncertainty \citep[e.g., the `crawl` R package][]\citep{Johnson:2008}.

## 4.1 | The future of `foieGras`
An older version of `foieGras` (v 0.7-6) is available on CRAN \url{https://CRAN.R-project.org/package=foieGras}, this version does not have all the features described here and will be archived by CRAN eventually. The current `foieGras` version (v 1.1) is available from the R-universe repository \url{https://ianjonsen.r-universe.dev/ui#package:foieGras}, and can be installed from source within R via `install.packages("foieGras", repos = "https://ianjonsen.r-universe.dev")`. Other installation options exist and we refer users to additional information here \url{https://github.com/ianjonsen/foieGras}. 

The `foieGras` package will undergo further development, expanding the range of available SSM's via new movement process models and/or enhanced measurement models for other electronic tracking data types. Additionally, we will seek to enhance integration with other R packages for processing and analysis of animal movement data, where feasible. Feedback from users is invaluable and encouraged. Users may submit bug reports and enhancement suggestions via the foieGras GitHub issues page (https://github.com/ianjonsen/foieGras/issues/new/choose). More general feedback is always welcome by contacting the lead author directly.
