---
title: "foieGras an R package for rapid quality control, behavioural estimation and simulation of animal track data"
header-includes:
  - \usepackage{lineno}
    \usepackage{placeins}
    \linenumbers
compact-title: FALSE
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
        in_header:
          - preamble.sty
documentclass: "article"
classoption: "11pt"
geometry: left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm,headheight=12pt,a4paper
bibliography: refs.bib
csl: methods-in-ecology-and-evolution.csl
spacing: double
---

```{r knitr_setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=TRUE,
                      warning=FALSE,
                      cache=TRUE,
                      autodep=TRUE,
                      fig.path="../figures/",
                      #to handle remaining figures without indices
                      #From:https://github.com/yihui/knitr/issues/505
                      fig.process = function(x) {
                        x2 = sub('-\\d+[.][a-z]+)$', '\\1', x)
                        if (file.rename(x, x2)) x2 else x 
                        }
                      )
```

```{r setup, include=FALSE, cache=FALSE}
#### Setup ####
## all the packages needed for this tutorial are listed here
library(foieGras)
library(mpmm)
library(ggplot2)
library(ggthemes)
library(patchwork)
library(dplyr)
library(lubridate)
library(kableExtra)
library(knitr)
library(docxtools)
library(tibble)
library(gratia)
library(latex2exp)

## set the default theme for ggplot objects to theme_minimal()
theme_set(theme_minimal())
theme_update(panel.grid.major = element_line(size = 0.25),
             panel.grid.minor = element_line(size = 0.15))

# check for the R version number and if less than 3.6, switch to using the
# new random number generator, to ensure replicability

if(getRversion() < 3.6) RNGversion("3.6.0")
```

```{r setup_tables, include=FALSE, purl=FALSE}
#This code is for configuring latex tables. It is not needed for general script
#usage.
table_out_format <- ifelse("pdf_document" %in% rmarkdown::all_output_formats("../paper_sections/full_document.Rmd"),
                    "latex",
                     ifelse("html_document" %in% rmarkdown::all_output_formats("../paper_sections/full_document.Rmd"),
                            "html",
                            NA_character_)
                      )
```

# Abstract
text...

```{r child = '01-intro.Rmd'}
```
\FloatBarrier
```{r child = '02-foieGras_overview.Rmd'}
```
\FloatBarrier
```{r child = '03-data_prep.Rmd'}
```
\FloatBarrier
```{r child = '04-ssm_fitting.Rmd'}
```
\FloatBarrier
```{r child = '05-visualisation_diagnostics.Rmd'}
```
\FloatBarrier
```{r child = '06-behavioural_estimation.Rmd'}
```
\FloatBarrier
```{r child = '07-extending_the_behavioural_model.Rmd'}
```
\FloatBarrier
```{r child = '08-simulation.Rmd'}
```
\FloatBarrier
```{r child = '09-examples.Rmd'}
```
\FloatBarrier
```{r child = '10-discussion.Rmd'}
```

# Acknowledgements

# Author's Contributions

# Data Accessibility

# ORCID

# Bibliography
